## Section A: Data Structures & Control Structures

#### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [31]:
a=[1,2,3,4]
# append
a.append(5)
print(f'a={a}')

#extend 
b=[6,7,8]
a.extend(b)
print(f'a={a}')

#insert
b.insert(3,10)
print(f'b={b}')

#remove
a.remove(8)
print(f'a={a}')

#pop
b.pop()
print(f'b={b}')

#clear
a.clear()
print(f'a={a}')

#index
m=b.index(7)
print(m)

#count
l1=[21,30,21,28]
c=l1.count(21)
print(c)

#sort
l1.sort()
print(l1)

#reverse
l1.reverse()
print(l1)

a=[1, 2, 3, 4, 5]
a=[1, 2, 3, 4, 5, 6, 7, 8]
b=[6, 7, 8, 10]
a=[1, 2, 3, 4, 5, 6, 7]
b=[6, 7, 8]
a=[]
1
2
[21, 21, 28, 30]
[30, 28, 21, 21]

#### 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why

In [1]:
t2 = ['luffy', 'zoro', 'robin']
t2[1] = 'sanji'
print(t2)

['luffy', 'sanji', 'robin']

In [5]:
t1[2]='sanji'

TypeError: 'tuple' object does not support item assignment

###### When you try  to make a change to a tuple it throws type error because tuple is an immutable object. THe values in a tuple are fixed cannot be changed.

### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [6]:
nums={1,2,3,2,1,5,4}
print(nums)

{1, 2, 3, 4, 5}

### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [7]:
dict1 = { 'name':'thomas',
         'age':23,
         'city':'bengaluru'}
print(dict1)

{'name': 'thomas', 'age': 23, 'city': 'bengaluru'}

In [10]:
dict1['age']=25
dict1

{'name': 'thomas', 'age': 25, 'city': 'bengaluru'}

In [14]:
dict1.setdefault('email','thomas121@gmail.com')

'thomas121@gmail.com'

In [15]:
dict1

{'name': 'thomas',
 'age': 25,
 'city': 'bengaluru',
 'email': 'thomas121@gmail.com'}

### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [19]:
age=int(input('Enter the age : '))
if age>=18:
    print('Eligible to vote')
else:
    print('Not eligible to vote')

Enter the age :  22

Eligible to vote

### 6.	Given a 'marks' variable, print the grade:
### - 90 and above: 'A'
### - 75–89: 'B'
### - 50–74: 'C'
### - Below 50: 'Fail'

In [20]:
marks = int(input('Enter the marks'))
if marks>=90:
    print('A')
elif marks>=75 :
    print('B')
elif marks>=50:
    print('C')
else:
    print('Fail')

Enter the marks 75

B

### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [27]:
n=int(input('Enter a number'))
if n==0:
    print('0 is neither postive nor negative')
if n>0:
    if n%2==0:
        print('Positive and even')
    else:
        print('Positive and odd')
if n<0:
    if n%2==0:
        print('Negative and even')
    else:
        print('Negative and odd')

Enter a number 7

Positive and odd

### Section B: Numpy
### 8.	Create:
### - A scalar using np.array(5)
### - A 1D array with values 1 to 5
### - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [28]:
import numpy as np

In [29]:
np.array(5)

array(5)

In [33]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [34]:
two_d = np.arange(10, 70, 10).reshape(2, 3)
print(two_d)

[[10 20 30]
 [40 50 60]]

### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [35]:

arr_4x4 = np.random.randint(0, 101, (4, 4))
print(arr_4x4)

[[38 42 36 40]
 [18 55 25 92]
 [42 92 21 23]
 [69  7 84 72]]

### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [36]:
import pandas as pd
arr_3x3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

df = pd.DataFrame(arr_3x3, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
### - Use .info(), .describe()
### - Select 'Name' and 'City' columns
### - Drop 'City' column
### - Fill any missing values in 'Salary' column with the mean
### - Remove any duplicate rows

In [2]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Asha', 'Raj', 'Neha', 'Vikram', 'Sara', 'Asha', 'Kiran', 'Meena', 'Raj', 'Tara'],
    'Age': [25, 30, 22, 28, 26, 25, 32, 29, 30, 27],
    'City': ['Bangalore', 'Delhi', 'Mumbai', 'Chennai', 'Pune', 'Bangalore', 'Hyderabad', 'Kolkata', 'Delhi', 'Goa'],
    'Salary': [50000, 60000, np.nan, 55000, 52000, 50000, 65000, np.nan, 60000, 58000]
}

In [5]:
df=pd.DataFrame(data)
df

     Name  Age       City   Salary
0    Asha   25  Bangalore  50000.0
1     Raj   30      Delhi  60000.0
2    Neha   22     Mumbai      NaN
3  Vikram   28    Chennai  55000.0
4    Sara   26       Pune  52000.0
5    Asha   25  Bangalore  50000.0
6   Kiran   32  Hyderabad  65000.0
7   Meena   29    Kolkata      NaN
8     Raj   30      Delhi  60000.0
9    Tara   27        Goa  58000.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [7]:
df.describe()

             Age       Salary
count  10.000000      8.00000
mean   27.400000  56250.00000
std     2.988868   5418.22322
min    22.000000  50000.00000
25%    25.250000  51500.00000
50%    27.500000  56500.00000
75%    29.750000  60000.00000
max    32.000000  65000.00000

In [13]:
print(df[['Name','City']])

     Name       City
0    Asha  Bangalore
1     Raj      Delhi
2    Neha     Mumbai
3  Vikram    Chennai
4    Sara       Pune
5    Asha  Bangalore
6   Kiran  Hyderabad
7   Meena    Kolkata
8     Raj      Delhi
9    Tara        Goa

In [9]:
mean_sal=df['Salary'].mean()

In [16]:
df['Salary']=df['Salary'].fillna(mean_sal)
df

     Name  Age       City   Salary
0    Asha   25  Bangalore  50000.0
1     Raj   30      Delhi  60000.0
2    Neha   22     Mumbai  56250.0
3  Vikram   28    Chennai  55000.0
4    Sara   26       Pune  52000.0
5    Asha   25  Bangalore  50000.0
6   Kiran   32  Hyderabad  65000.0
7   Meena   29    Kolkata  56250.0
8     Raj   30      Delhi  60000.0
9    Tara   27        Goa  58000.0

In [17]:
df.drop_duplicates()

     Name  Age       City   Salary
0    Asha   25  Bangalore  50000.0
1     Raj   30      Delhi  60000.0
2    Neha   22     Mumbai  56250.0
3  Vikram   28    Chennai  55000.0
4    Sara   26       Pune  52000.0
6   Kiran   32  Hyderabad  65000.0
7   Meena   29    Kolkata  56250.0
9    Tara   27        Goa  58000.0