### 1.	Handle missing values as per the best practices (imputation, removal, etc.).
##### ●	Apply scaling techniques to numerical features:
##### a.	Standard Scalingb. Min-Max Scaling
##### ●	Discuss the scenarios where each scaling technique is preferred and why.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('adult_with_headers (1).csv')

In [4]:
data

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [5]:
data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [12]:
data.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [6]:
### There are no missing values in this data

In [7]:
from sklearn.preprocessing import StandardScaler

In [14]:
# TASK 2a: Standard Scaling
num_cols = ['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week']
scaler_standard = StandardScaler()
df_standard = data.copy()
df_standard[num_cols] = scaler_standard.fit_transform(data[num_cols])
print("\nStandard Scaling applied to:", num_cols)

Standard Scaling applied to: ['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week']

In [16]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder

In [24]:
# TASK 2b: Min-Max Scaling
scaler_minmax = MinMaxScaler()
df_minmax = data.copy()
df_minmax[num_cols] = scaler_minmax.fit_transform(data[num_cols])
print("Min-Max Scaling applied to:", num_cols)

Min-Max Scaling applied to: ['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week']

####  2 Encoding Techniques:
##### ●	Apply One-Hot Encoding to categorical variables with less than 5 categories.
##### ●	Use Label Encoding for categorical variables. Data Exploration and Preprocessing:
##### ●	Load the dataset and conduct basic data exploration (summary statistics, missing values, data types).
##### ●	les with more than 5 categories.
##### ●	Discuss the pros and cons of One-Hot Encoding and Label Encoding.

In [20]:

# Low cardinality (<5 categories): One-Hot Encoding
low_card = ['relationship', 'race', 'sex']
df_encoded = pd.get_dummies(data, columns=low_card, prefix=low_card)

# High cardinality (>5 categories): Label Encoding
high_card = ['workclass', 'education', 'marital_status', 'occupation', 'native_country']
le = LabelEncoder()
for col in high_card:
    df_encoded[col] = le.fit_transform(df_encoded[col].astype(str))

print("\nEncoding completed.")

Encoding completed.

#### One-Hot Encoding Pros and Cons
##### Creates binary columns per category (e.g., sex_Male, sex_Female), avoiding false ordinal relationships. Ideal for nominal data like race or relationship in your Adult dataset where no natural order exists. Works best with linear models, neural networks, and distance-based algorithms (KNN).​

##### Cons: Explodes dimensionality with high-cardinality features (e.g., native_country with 42 categories becomes 42 sparse columns). Increases memory usage and training time; risks multicollinearity in logistic regression.

#### 3.Feature Engineering:
##### ●	Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.
##### ●	Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.

In [21]:
# Feature 3: Log transform skewed capital_gain
data['log_capital_gain'] = np.log1p(data['capital_gain'])
print("New features created: income_binary, age_group, log_capital_gain")

# Verify transformations
print("\nSkewness before/after log transform:")
print("capital_gain skewness:", data['capital_gain'].skew())
print("log_capital_gain skewness:", data['log_capital_gain'].skew())

# Save processed dataset
data.to_csv('adult_processed.csv', index=False)
print("\nProcessed data saved as 'adult_processed.csv'")

New features created: income_binary, age_group, log_capital_gain

Skewness before/after log transform:
capital_gain skewness: 11.953847687699799
log_capital_gain skewness: 3.096143524467517

Processed data saved as 'adult_processed.csv'

##### Log transformation was applied to capital_gain because it exhibits extreme right-skewness (skewness ≈14.9).
##### 99% of capital_gain values equal 0 (no capital gains), while 1% have extreme values up to 99,999. This creates massive leverage points that dominate distance-based models (KNN, SVM) and gradient descent (neural networks). Log transformation compresses the right tail: ln(1+99999) = 11.51 vs ln(1+0) = 0.

In [22]:
new_data=pd.read_csv('adult_processed.csv')
new_data

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,log_capital_gain
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,7.684784
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0.000000
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0.000000
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0.000000
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,0.000000
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,0.000000
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,0.000000
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,0.000000
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,9.617471